-- SCRIPT DE CARGA - DEPARTAMENTO
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Administrativo');	
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Atendimento ao cliente');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Auditoria');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Comercial');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Compras');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Comunicação');	
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Contabilidade');	
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Marketing');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Operações');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Recursos Humanos');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('TI – Tecnologia da Informação');
INSERT INTO EN_DEPARTAMENTO(DESC_DEPARTAMENTO) VALUES ('Vendas');

-- SCRIPT DE CARGA - CARGO

INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Gerente de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Coordenador de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Supervisor de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Consultor de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Analista de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Analista de Requisitos');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Analista de Testes');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Trainee de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Assistente de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Auxiliar de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Estagiário de Sistemas');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Diretor de Suporte Técnico em TI');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Coordenador de Suporte Técnico em TI');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Supervisor de Suporte Técnico em TI');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Consultor de Suporte Técnico em TI');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Analista de Suporte Técnico em TI');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Diretor de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Gerente de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Consultor de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Coordenador de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Supervisor de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Analista de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Trainee de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Assistente de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Auxiliar de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Estagiário de Tecnologia da Informação');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Diretor de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Gerente de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Coordenador de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Supervisor de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Analista de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Trainee de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Assistente de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Auxiliar de Web Development');
INSERT INTO EN_CARGO(DESC_CARGO) VALUES ('Estagiário de Web Development');


INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 01', 1,1,'Biografia Pessoa 01');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 02', 2,2,'Biografia Pessoa 02');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 03', 3,3,'Biografia Pessoa 03');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 04', 4,4,'Biografia Pessoa 04');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 05', 5,5,'Biografia Pessoa 05');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 06', 6,6,'Biografia Pessoa 06');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 07', 7,7,'Biografia Pessoa 07');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 08', 8,8,'Biografia Pessoa 08');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 09', 9,9,'Biografia Pessoa 09');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 10', 10,10,'Biografia Pessoa 10');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 11', 11,11,'Biografia Pessoa 11');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 12', 12,12,'Biografia Pessoa 12');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 13', 13,1,'Biografia Pessoa 13');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 14', 14,2,'Biografia Pessoa 14');
INSERT INTO EN_COLABORADOR(NME_COLABORADOR, NRO_ID_CARGO, NRO_ID_DEPARTAMENTO, TXT_BIOGRAFIA) VALUES('Pessoa 15', 15,3,'Biografia Pessoa 15');
